language: java
deploy:
  provider: cloudfoundry
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: $CF_ORG
  space: $CF_SPACE
  api: $CF_API_URL
  manifest: manifest.yml
  on:
    all_branches: true